# Generated by Django 4.1.2 on 2022-10-07 21:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YelpUser",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=22, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("review_count", models.PositiveIntegerField()),
                ("yelping_since", models.DateField()),
                ("useful", models.PositiveIntegerField()),
                ("funny", models.PositiveBigIntegerField()),
                ("cool", models.PositiveBigIntegerField()),
                ("fans", models.PositiveIntegerField()),
                (
                    "elite",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(blank=True), size=50
                    ),
                ),
                ("average_stars", models.FloatField()),
                ("compliment_hot", models.PositiveIntegerField()),
                ("compliment_more", models.PositiveIntegerField()),
                ("compliment_profile", models.PositiveIntegerField()),
                ("compliment_cute", models.PositiveIntegerField()),
                ("compliment_list", models.PositiveIntegerField()),
                ("compliment_note", models.PositiveIntegerField()),
                ("compliment_plain", models.PositiveIntegerField()),
                ("compliment_cool", models.PositiveIntegerField()),
                ("compliment_funny", models.PositiveIntegerField()),
                ("compliment_writer", models.PositiveIntegerField()),
                ("compliment_photos", models.PositiveIntegerField()),
                ("friends", models.ManyToManyField(to="user.yelpuser")),
            ],
        ),
    ]
