# Generated by Django 4.1.2 on 2022-10-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_yelpuser_yelping_since"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yelpuser",
            name="compliment_cool",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="compliment_cute",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="compliment_funny",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="compliment_hot",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="compliment_list",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="compliment_more",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="compliment_note",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="compliment_photos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="compliment_plain",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="compliment_profile",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="compliment_writer",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="cool",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="fans",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="funny",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yelpuser",
            name="useful",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
