# Generated by Django 4.1.2 on 2022-10-08 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0002_alter_business_attributes_alter_business_hours"),
        ("user", "0004_alter_yelpuser_compliment_cool_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "review_id",
                    models.CharField(max_length=22, primary_key=True, serialize=False),
                ),
                ("stars", models.FloatField(default=0)),
                ("useful", models.PositiveIntegerField(default=0)),
                ("funny", models.PositiveIntegerField(default=0)),
                ("cool", models.PositiveIntegerField(default=0)),
                ("text", models.TextField()),
                ("date", models.DateTimeField()),
                (
                    "business_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.business",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.yelpuser"
                    ),
                ),
            ],
        ),
    ]
