# Generated by Django 4.1.2 on 2022-10-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_attributes_alter_business_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='attributes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='hours',
            field=models.JSONField(null=True),
        ),
    ]
